require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ParsersController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Parser. As you add validations to Parser, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ParsersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all parsers as @parsers" do
      parser = Parser.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:parsers)).to eq([parser])
    end
  end

  describe "GET show" do
    it "assigns the requested parser as @parser" do
      parser = Parser.create! valid_attributes
      get :show, {:id => parser.to_param}, valid_session
      expect(assigns(:parser)).to eq(parser)
    end
  end

  describe "GET new" do
    it "assigns a new parser as @parser" do
      get :new, {}, valid_session
      expect(assigns(:parser)).to be_a_new(Parser)
    end
  end

  describe "GET edit" do
    it "assigns the requested parser as @parser" do
      parser = Parser.create! valid_attributes
      get :edit, {:id => parser.to_param}, valid_session
      expect(assigns(:parser)).to eq(parser)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Parser" do
        expect {
          post :create, {:parser => valid_attributes}, valid_session
        }.to change(Parser, :count).by(1)
      end

      it "assigns a newly created parser as @parser" do
        post :create, {:parser => valid_attributes}, valid_session
        expect(assigns(:parser)).to be_a(Parser)
        expect(assigns(:parser)).to be_persisted
      end

      it "redirects to the created parser" do
        post :create, {:parser => valid_attributes}, valid_session
        expect(response).to redirect_to(Parser.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved parser as @parser" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Parser).to receive(:save).and_return(false)
        post :create, {:parser => { "name" => "invalid value" }}, valid_session
        expect(assigns(:parser)).to be_a_new(Parser)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Parser).to receive(:save).and_return(false)
        post :create, {:parser => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested parser" do
        parser = Parser.create! valid_attributes
        # Assuming there are no other parsers in the database, this
        # specifies that the Parser created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        expect_any_instance_of(Parser).to receive(:update).with({ "name" => "MyString" })
        put :update, {:id => parser.to_param, :parser => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested parser as @parser" do
        parser = Parser.create! valid_attributes
        put :update, {:id => parser.to_param, :parser => valid_attributes}, valid_session
        expect(assigns(:parser)).to eq(parser)
      end

      it "redirects to the parser" do
        parser = Parser.create! valid_attributes
        put :update, {:id => parser.to_param, :parser => valid_attributes}, valid_session
        expect(response).to redirect_to(parser)
      end
    end

    describe "with invalid params" do
      it "assigns the parser as @parser" do
        parser = Parser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Parser).to receive(:update).and_return(false)
        put :update, {:id => parser.to_param, :parser => { "name" => "invalid value" }}, valid_session
        expect(assigns(:parser)).to eq(parser)
      end

      it "re-renders the 'edit' template" do
        parser = Parser.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        allow_any_instance_of(Parser).to receive(:update).and_return(false)
        put :update, {:id => parser.to_param, :parser => { "name" => "invalid value" }}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested parser" do
      parser = Parser.create! valid_attributes
      expect {
        delete :destroy, {:id => parser.to_param}, valid_session
      }.to change(Parser, :count).by(-1)
    end

    it "redirects to the parsers list" do
      parser = Parser.create! valid_attributes
      delete :destroy, {:id => parser.to_param}, valid_session
      expect(response).to redirect_to(parsers_url)
    end
  end

end
